version: "3"
services:
  ngnix:
    container_name: nginx-80
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - autumn-farm-wx

  mongodb:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345

  python:
    container_name: python
    image: mongo
    restart: unless-stopped

  autumn-farm-wx:
    container_name: autumn-farm-wx
    build:
      context: .
      args:
        port: 3000
    depends_on:
      - mongodb
      - python