version: "3"
services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017

  autumn-farm-wx:
    container_name: autumn-farm-wx
    build:
      context: .
      args:
        port: 3000
    ports:
      - 80:3000
    depends_on:
      - mongodb